### ISSUE TITLE
Example of MCQ setup using the Detailed Feedback plugin

### ISSUE THREAD

**Issue by SpacegoatHQ** [gowithfloat/adapt-detailed-feedback#1]
Hi,

Can you please add an example file showing where and how to add the detailed feedback to an MCQ?

Also, does it work with other Adapt code question types as well? (i.e. Graphical MCQ, Matching, Slider, Text input)

Thanks,
Peter

**Comment by mediabounds** [comment]
Hi, Peter,

Are you using the authoring tool?

In general, this extension is intended to be a drop-in replacement for Tutor. It only needs to be enabled for a whole course--there is no per-question configuration for the extension. Once it's enabled for the course, you should be good to go.

I think it's only been tested with the MCQ component. It was intended to show answer-specific feedback based on which option was chosen. But, if the other question components follow the same type of pattern, then it should work.

Hope that helps!
--Dan

**Comment by SpacegoatHQ** [comment]
Hi Dan,

Thanks for the quick reply. No, I'm actually using the framework. That's why I asked for a sample file - which I assume would be an example component block within the components.json. Also, to install, I guess I could download the ZIP, extract and then copy the folder into "src > components". Can you please confirm whether I can use this plugin with the framework as well? 

Re. the other question types, I might test ,once I get it to work with the classic MCQ.

Thanks,
Peter

**Comment by mediabounds** [comment]
You can use this plugin with the framework, but it will go within the src > extensions directory.

Then, you'll need to edit your `config.json` file and add two things:
1. Make sure the extension gets included in the course output by adding `adapt-detailed-feedback` to the `includes` array.
2. Enable the extension by adding the following to the config.json file (noted [here](https://github.com/gowithfloat/adapt-detailed-feedback/blob/master/example.json)):
```
"_detailedFeedback": {
    "_showDetailsBeforeLastAttempt": false,
    "_isEnabled": true
}
```

--Dan

**Comment by SpacegoatHQ** [comment]
Thanks again for the quick reply. OK thanks for confirming this can be used with the plugin and clarifying the install process. I saw the above in the readme file. What I'd like to get some further info about is how and where to add the answer specific detailed feedback. How would the standard **"_feedback"** block change to reflect the detailed feedback. I.e. Referring to your GIF demo here on Github, where to add the "January - Yes, January has 31 days" feedback for option 1.
Thanks

**Comment by mediabounds** [comment]
Ah, sorry for any confusion.
Those settings are actually a part of the [adapt-contrib-mcq](https://github.com/adaptlearning/adapt-contrib-mcq) component. If you look through the available settings, for each multiple choice item, there is also a `feedback` property. The feedback you enter there is referenced by this extension when displaying feedback.

--Dan

**Comment by SpacegoatHQ** [comment]
Yes, I know that... :-) I'm just wondering how they need to be changed to reflect the answer specific feedback. I.e. Where to put the "Yes, January has 31 days" feedback option to get it displayed when "January" is selected. Does it go inside an item within "_items" (e.g. "text", "_shouldBeSelected", and then "_detailedFeedback")? Or should it go into the "_feedback" block in some way? And if yes, what would be the format? As it only has the "correct", "_incorrect" etc. options in the default MCQ component.
P.S. sorry to keep bugging you, just need some clarification. Thanks

**Comment by mediabounds** [comment]
The answer-specific feedback goes within `_items`.

For example:
```
{
  ...
  "_items": [
    {
      "text": "This is option 1.",
      "_shouldBeSelected":true,
      "feedback":"Option one correct feedback"
    },
    {
      "text": "This is option 2.",
      "_shouldBeSelected":false,
      "feedback":"Option two incorrect feedback"
    },
    {
      "text": "This is option 3.",
      "_shouldBeSelected":false,
      "feedback":"Option three incorrect feedback"
    },
    {
      "text": "This is option 4.",
      "_shouldBeSelected":false,
      "feedback":"Option four incorrect feedback"
    }
  ],
  ...
}
```

Then once the detailed feedback extension is enabled, the feedback displayed will be based on whichever option was selected.

--Dan

**Comment by SpacegoatHQ** [comment]
Awesome! Exactly what I needed. Thanks Dan, really appreciate it! 

Maybe update the description / ReadMe.txt file here on Github as this part of the implementation is not clear.

Thanks again,
Peter
